# XDG
export XDG_CONFIG_HOME=$HOME/.config

# EDITOR
export EDITOR=nvim
export VISUAL=nvim

# ZSH
export ZDOTDIR=$XDG_CONFIG_HOME/zsh
export HISTFILE=$ZDOTDIR/.zhistory
export HISTSIZE=10000
export SAVEHIST=10000

# FIREFOX
export MOZ_ENABLE_WAYLAND=1

# WIREPLUMBER
export WIREPLUMBER_CONFIG_DIR=$XDG_CONFIG_DIR/wireplumber
export WIREPLUMBER_DATA_DIR=$WIREPLUMBER_CONFIG_DIR/scripts
