#!/usr/bin/env fish

set session (find -L ~ ~/progs -mindepth 1 -maxdepth 1 -type d | fzf)

if test -z $session
    exit 0
end

set session_name (basename $session | tr . _)

tmux has-session -t $session_name 2>/dev/null
or tmux new-session -s $session_name -c $session -d

if set -q TMUX
    tmux switch-client -t $session_name
else
    tmux attach-session -t $session_name
end
