#!/usr/bin/env fish

set session (find -L ~ ~/progs -mindepth 1 -maxdepth 1 -type d | fzf)

if test -z $session
    exit 0
end

set session_name (basename $session | tr . _)


if set -q TMUX
    tmux neww -n $session_name -c $session
    tmux switch-client -t $session_name
    exit 0
else
    if not tmux has-session -t $session_name 2>/dev/null
        tmux new-session -s $session_name -c $session -d
    end
    tmux attach-session -t $session_name
end
